name: natker_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.9.3
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  ficonsax: ^0.0.3
  firebase_auth: ^4.10.1
  firebase_auth_platform_interface: ^6.19.1
  firebase_core: ^2.17.0
  firebase_core_platform_interface: ^4.8.0
  firebase_database: ^10.2.7
  firebase_dynamic_links: ^5.3.7
  firebase_storage: ^11.2.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_facebook_auth: ^6.0.2
  flutter_share: ^2.0.0
  formz: ^0.6.1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  social_login_buttons: ^1.0.7
  twitter_login: ^4.4.2
  very_good_analysis: ^5.1.0
  json_serializable: ^6.7.1

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.3
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/